# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      timeout-minutes: 5
      run: |
        set -x
        sudo apt-get update
        sudo apt-get install -y debootstrap systemd-container
        sudo debootstrap xenial ~/ubuntu-xenial-tree/ http://archive.ubuntu.com/ubuntu/
        sudo systemd-nspawn -D ~/ubuntu-xenial-tree/
        sudo machinectl list-images

        sudo machinectl export-tar ubuntu-xenial-tree ubuntu-xenial.gz
        sudo machinectl list-transfers
        echo "what else is here?"
        ls -lisah
        find .

        sleep 5 
        sudo machinectl list-transfers

        ls -lisah
        find .

        sleep 60
        sudo machinectl list-transfers
        ls -lisah
        find .
        

        #sudo debootstrap --variant=buildd --arch i386 hardy /var/chroot/hardy http://archive.ubuntu.com/ubuntu/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        path: ubuntu-xenial.gz
